variable "sg_name" {}
variable "network_name" {}
variable "public_subnet_name" {}
variable "private_subnet_name" {}
variable "address_space" {}
variable "private_subnet_address_prefixes" {}
variable "public_subnet_address_prefixes" {}
variable "network_rules" {}
variable "private_subnet_nsg_name" {}
variable "rg_name" {}
variable "location" {}